-- ==============================================
-- Full Schema and Dummy Data for KlinikSehat
-- Run this script in the Supabase SQL Editor
-- ==============================================

-- Reset existing tables (this wipes the previous dummy data so we can recreate securely)
DROP TABLE IF EXISTS public.reservations CASCADE;
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TABLE IF EXISTS public.doctors CASCADE;

-- 1. Create Storage Bucket for Images (Doctors & Articles)
INSERT INTO storage.buckets (id, name, public) VALUES ('clinic-images', 'clinic-images', true) ON CONFLICT DO NOTHING;

-- Storage Policies
-- Allow public access to read images
CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING (bucket_id = 'clinic-images');
-- Allow authenticated admins to upload/update/delete images
CREATE POLICY "Admin Upload Access" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'clinic-images' AND auth.role() = 'authenticated');
CREATE POLICY "Admin Update Access" ON storage.objects FOR UPDATE USING (bucket_id = 'clinic-images' AND auth.role() = 'authenticated');
CREATE POLICY "Admin Delete Access" ON storage.objects FOR DELETE USING (bucket_id = 'clinic-images' AND auth.role() = 'authenticated');


-- 2. Create Doctors Table
CREATE TABLE public.doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT NOT NULL,
  image_url TEXT,
  schedule TEXT,
  experience TEXT,
  rating NUMERIC(3, 1),
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Doctor RLS Policies
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.doctors FOR SELECT USING (true);
CREATE POLICY "Admins can insert/update doctors" ON public.doctors FOR ALL USING (auth.role() = 'authenticated');

-- Insert Dummy Data for Doctors
INSERT INTO public.doctors (name, specialty, schedule, experience, rating, bio, image_url) VALUES
('dr. Ahmad Fauzi, Sp.PD', 'Spesialis Penyakit Dalam', 'Senin - Jumat, 08:00 - 14:00', '15 Tahun', 4.9, 'Berpengalaman menangani penyakit dalam dengan teknologi modern.', 'https://placehold.co/400x400/0d9488/ffffff?text=Dr.+Ahmad'),
('drg. Budi Santoso', 'Dokter Gigi', 'Selasa, Kamis, Sabtu, 10:00 - 17:00', '8 Tahun', 4.9, 'Ahli dalam perawatan gigi estetika dan restorasi.', 'https://placehold.co/400x400/0891b2/ffffff?text=Drg.+Budi'),
('dr. Rina Kartika, Sp.A', 'Spesialis Anak', 'Senin - Sabtu, 09:00 - 16:00', '12 Tahun', 4.8, 'Pendekatan ramah anak untuk tumbuh kembang optimal.', 'https://placehold.co/400x400/0f766e/ffffff?text=Dr.+Rina');


-- 3. Create Articles Table
CREATE TABLE public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT,
  read_time TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Article RLS Policies
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public articles are viewable by everyone." ON public.articles FOR SELECT USING (true);
CREATE POLICY "Admins can insert/update articles" ON public.articles FOR ALL USING (auth.role() = 'authenticated');

-- Insert Dummy Data for Articles
INSERT INTO public.articles (title, excerpt, content, category, read_time, image_url) VALUES
('Pentingnya Medical Check Up Rutin', 'Ketahui mengapa pemeriksaan kesehatan rutin sangat penting untuk deteksi dini penyakit mematikan.', 'Medical check-up sangat krusial bagi kesehatan...', 'Kesehatan Umum', '5 Menit', 'https://placehold.co/600x400/0f172a/ffffff?text=Medical+Check+Up'),
('Cara Menjaga Kesehatan Jantung', 'Tips sederhana menjaga performa jantung tetap prima di usia produktif dengan pola makan sehat.', 'Jantung adalah organ vital...', 'Jantung', '4 Menit', 'https://placehold.co/600x400/0f172a/ffffff?text=Kesehatan+Jantung'),
('Mitos dan Fakta Seputar Gigi Berlubang', 'Jangan sampai salah kaprah! Simak penjelasan dokter spesialis gigi mengenai sakit gigi berlubang.', 'Banyak yang mengira ulat gigi...', 'Kesehatan Gigi', '3 Menit', 'https://placehold.co/600x400/0f172a/ffffff?text=Kesehatan+Gigi');


-- 4. Create Reservations Table
CREATE TABLE public.reservations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reservation_code TEXT UNIQUE NOT NULL,
  patient_name TEXT NOT NULL,
  patient_phone TEXT NOT NULL,
  doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL,
  reservation_date DATE NOT NULL,
  reservation_time TIME NOT NULL,
  complaint TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Reservation RLS Policies
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can create a reservation" ON public.reservations FOR INSERT WITH CHECK (true);
CREATE POLICY "Only admins can view/update reservations" ON public.reservations FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Only admins can update reservations" ON public.reservations FOR UPDATE USING (auth.role() = 'authenticated');

-- Insert Dummy Data for Reservations
INSERT INTO public.reservations (reservation_code, patient_name, patient_phone, doctor_id, reservation_date, reservation_time, status) VALUES
('RSV-001', 'Budi Santoso', '081234567890', 1, '2026-03-21', '09:00:00', 'confirmed'),
('RSV-002', 'Siti Aminah', '081234567891', 2, '2026-03-21', '10:00:00', 'pending'),
('RSV-003', 'Andi Pratama', '081234567892', 3, '2026-03-21', '11:00:00', 'confirmed');
